name: 'Array Element Template'
description: 'Apply a uniform template to each array element for consistent string formatting.'
author: 'Andrew Keller'
branding:
  icon: 'type'
  color: 'orange'
inputs:
  array:
    description: 'Array containing the elements to which the template will be applied.'
    required: true
    default: ''
  template:
    description: 'String template that defines the format to be applied to each element in the array.'
    required: true
    default: ''
  word-delimiter:
    description: 'Delimiter to be used between words. Note: This can only separate words by existing symbols or changes in letter case.'
    required: false
    default: 'none'
  case:
    description: 'String case of array element in output. Options: `upper`, `lower`, `camel`, `pascal`.'
    required: false
    default: 'none'
  validation-pattern:
    description: 'Validation pattern for array elements. Defaults to `^[a-zA-Z0-9 _./-]+$`. Warning: Update only when input is trusted.'
    required: false
    default: '^[a-zA-Z0-9 _./-]+$'
outputs:
  formatted-array:
    description: 'Array with each element formatted to the specified template.'
    value: ${{ steps.concat-array.outputs.formatted-array }}
  formatted-string:
    description: 'String with each array element formatted to the specified template.'
    value: ${{ steps.concat-array.outputs.formatted-string }}
runs:
  using: 'composite'
  steps:
    - name: Extract branch, tag, or PR base branch name
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "REF_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
        else
          ref="${GITHUB_REF#refs/}"
          if [[ "$ref" == "tags/"* ]]; then
            echo "REF_NAME=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
          elif [[ "$ref" == "heads/"* ]]; then
            echo "REF_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          fi
        fi
      shell: bash
      env:
        GITHUB_REF: ${{ github.ref }}

    - name: Use current ref name
      run: echo "Current ref is ${{ env.REF_NAME }}"
      shell: bash

    - name: Checkout action repository
      uses: actions/checkout@v3
      with:
        repository: 'palacera/github-action-array-element-template'
        ref: ${{ env.REF_NAME }}
        path: 'action-array-element-template'

    - id: concat-array
      run: |
        IFS=' ' read -ra ARRAY <<< "${{ inputs.array }}"
        array_output=$(python3 action-array-element-template/array_element_template.py \
        -a "${ARRAY[@]}" \
        -t "${{ inputs.template }}" \
        -c "${{ inputs.case }}" \
        -w "${{ inputs.word-delimiter }}" \
        -p "${{ inputs.validation-pattern }}")
        string_output="${array_output[*]}"
        echo "formatted-array=$array_output" >> $GITHUB_OUTPUT
        echo "formatted-string=$string_output" >> $GITHUB_OUTPUT
      shell: bash
